# Identifiants des bases. En production : SealedSecrets / External Secrets, jamais en clair dans Git.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-hotels
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  POSTGRES_DB: hotels
  POSTGRES_USER: hotels
  POSTGRES_PASSWORD: hotels
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-reservations
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  POSTGRES_DB: reservations
  POSTGRES_USER: reservations
  POSTGRES_PASSWORD: reservations
